#Creating a service account named jenkins
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: devops

---

#Defining role that grants permissions in the devops namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-role
  namespace: devops
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "secrets"] #Allow to manage pods, access logs, create services and image pull
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"] #Allow to deploy and update applications
    verbs: ["get", "watch", "list", "create", "delete", "patch", "update"]

---
#Binding role to the jenkins serviceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-role-binding
  namespace: devops
subjects:
  - kind: ServiceAccount #Binding to serviceAccount
    name: jenkins
    namespace: devops
roleRef:
  kind: Role #Binding to a role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io